# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import EventResult, EventState, FileRole


class OneGeneral(BaseModel):
    node: Optional[
        Annotated[
            Union["OneGeneralNodeNode", "OneGeneralNodeGeneralTask"],
            Field(discriminator="typename__"),
        ]
    ]


class OneGeneralNodeNode(BaseModel):
    typename__: Literal[
        "AggregateInversionSolution",
        "AutomationTask",
        "File",
        "InversionSolution",
        "InversionSolutionNrml",
        "Node",
        "ObjectIdentity",
        "OpenquakeHazardConfig",
        "OpenquakeHazardSolution",
        "OpenquakeHazardTask",
        "RuptureGenerationTask",
        "ScaledInversionSolution",
        "SmsFile",
        "StrongMotionStation",
        "Table",
        "TimeDependentInversionSolution",
    ] = Field(alias="__typename")


class OneGeneralNodeGeneralTask(BaseModel):
    typename__: Literal["GeneralTask"] = Field(alias="__typename")
    title: Optional[str]
    created: Optional[Any]
    children: Optional["OneGeneralNodeGeneralTaskChildren"]


class OneGeneralNodeGeneralTaskChildren(BaseModel):
    edges: List[Optional["OneGeneralNodeGeneralTaskChildrenEdges"]]


class OneGeneralNodeGeneralTaskChildrenEdges(BaseModel):
    node: Optional["OneGeneralNodeGeneralTaskChildrenEdgesNode"]


class OneGeneralNodeGeneralTaskChildrenEdgesNode(BaseModel):
    child: Optional[
        Annotated[
            Union[
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildGeneralTask",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTask",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildAutomationTask",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildOpenquakeHazardTask",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildGeneralTask(BaseModel):
    typename__: Literal["GeneralTask"] = Field(alias="__typename")
    id: str


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTask(BaseModel):
    typename__: Literal["RuptureGenerationTask"] = Field(alias="__typename")
    id: str
    created: Optional[Any]
    state: Optional[EventState]
    result: Optional[EventResult]
    arguments: Optional[
        List[
            Optional[
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskArguments"
            ]
        ]
    ]
    files: Optional[
        "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFiles"
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskArguments(
    BaseModel
):
    k: Optional[str]
    v: Optional[str]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFiles(
    BaseModel
):
    edges: List[
        Optional[
            "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdges"
        ]
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdges(
    BaseModel
):
    node: Optional[
        "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNode"
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNode(
    BaseModel
):
    role: FileRole
    file: Optional[
        Annotated[
            Union[
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileSmsFile",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileFile",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileInversionSolution",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileScaledInversionSolution",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileAggregateInversionSolution",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileInversionSolutionNrml",
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileTimeDependentInversionSolution",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileSmsFile(
    BaseModel
):
    typename__: Literal["SmsFile"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileFile(
    BaseModel
):
    typename__: Literal["File"] = Field(alias="__typename")
    id: str
    file_name: Optional[str]
    file_size: Optional[Any]
    meta: Optional[
        List[
            Optional[
                "OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileFileMeta"
            ]
        ]
    ]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileFileMeta(
    BaseModel
):
    k: Optional[str]
    v: Optional[str]


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileInversionSolution(
    BaseModel
):
    typename__: Literal["InversionSolution"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileScaledInversionSolution(
    BaseModel
):
    typename__: Literal["ScaledInversionSolution"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileAggregateInversionSolution(
    BaseModel
):
    typename__: Literal["AggregateInversionSolution"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileInversionSolutionNrml(
    BaseModel
):
    typename__: Literal["InversionSolutionNrml"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileTimeDependentInversionSolution(
    BaseModel
):
    typename__: Literal["TimeDependentInversionSolution"] = Field(alias="__typename")


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildAutomationTask(BaseModel):
    typename__: Literal["AutomationTask"] = Field(alias="__typename")
    id: str


class OneGeneralNodeGeneralTaskChildrenEdgesNodeChildOpenquakeHazardTask(BaseModel):
    typename__: Literal["OpenquakeHazardTask"] = Field(alias="__typename")
    id: str


OneGeneral.model_rebuild()
OneGeneralNodeGeneralTask.model_rebuild()
OneGeneralNodeGeneralTaskChildren.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdges.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNode.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTask.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFiles.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdges.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNode.model_rebuild()
OneGeneralNodeGeneralTaskChildrenEdgesNodeChildRuptureGenerationTaskFilesEdgesNodeFileFile.model_rebuild()
