name: Dev workflow

on:
  pull_request:
    branches: [main, deploy-test]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      # re-enable Windows after https://github.com/GNS-Science/nshm-toshi-client/issues/28
      operating-systems: "['ubuntu-latest', 'macos-latest']" # "['ubuntu-latest', 'macos-latest', 'windows-latest']"
      python-versions: "['3.9', '3.10']"
    secrets: inherit
